Repository mojs/mojs, pull requests merged in 2019-03, with the labels that each got.

#150 Update jsDelivr link
  readme.md
Labels: bug

#208 Converts documentation links to HTTPS
  api/burst.md
  api/easing/approximate.md
  api/easing/base-functions.md
  api/easing/bezier-curves.md
  api/easing/path-easing.md
  api/html.md
  api/shape-swirl.md
  api/shape.md
  api/stagger.md
  api/syntax/property-maps.md
  api/syntax/rand.md
  api/syntax/stagger.md
  api/syntax/units.md
  api/tweens/timeline.md
  api/tweens/tween.md
  build/mo.js
  js/easing/bezier-easing.coffee
  js/easing/path-easing.coffee
  js/motion-path.coffee
  js/vendor/resize.coffee
  readme.md
  spec/shapes/bit.coffee
  spec/shapes/bit.coffee.html
Labels: optimization

#164 Fix Sauce Lab config for Travis tests
  .travis.yml
  karma.conf.js
Labels: optimization

#176 Adding introductory post by Sarah Drasner
  readme.md
Labels: documentation

#202 Fix mojs.io domain
  readme.md
Labels: bug, critical
