Repository mojs/mojs, pull requests merged in 2020-10, with the labels that each got.

#241 Migrate to Github Actions
  .github/workflows/ci.yml
  .github/workflows/publish-package.yml
  .npmignore
  .travis.yml
  README.md
  karma.conf.js
  package-lock.json
  package.json
Labels: core

#245 ESLint
  .eslintignore
  .eslintrc
  .github/workflows/ci.yml
  karma.conf.js
  package-lock.json
  package.json
  src/burst.babel.js
  src/delta/delta.babel.js
  src/delta/deltas.babel.js
  src/easing/approximate-map.babel.js
  src/easing/approximate.babel.js
  src/html.babel.js
  src/module.babel.js
  src/mojs.babel.js
  src/shape-swirl.babel.js
  src/shape.babel.js
  src/shapes/bit.babel.js
  src/shapes/curve.babel.js
  src/shapes/custom.babel.js
  src/spriter.babel.js
  src/stagger.babel.js
  src/thenable.babel.js
  src/tunable.babel.js
  src/tween/timeline.babel.js
  src/tween/tween.babel.js
  src/tween/tweenable.babel.js
  src/tween/tweener.babel.js
  webpack.common.js
  webpack.dev.js
  webpack.umd.js
Labels: core, optimization

#240 Add developer focused info about the build system
  CONTRIBUTING.md
Labels: documentation
